title: rpoCdb
description: Documentation for the rpoC Database
theme: just-the-docs

url: https://rpocdb.github.io/

logo: /assets/rpocdb_logo.png

aux_links:
  GitHub Repo: https://github.com/rpoCdb/rpoCdatabase

nav_enabled: true

color_scheme: light

search_enabled: true

favicon_ico: /assets/icon.png