title: rpoCdb
description: Documentation for the rpoC Database
theme: just-the-docs

url: https://rpocdb.github.io/

logo: /assets/rpocdb_logo.png

aux_links:
  GitHub Repo: https://github.com/rpoCdb/rpoCdatabase

nav_enabled: true

color_scheme: light

search_enabled: true

favicon_ico: /assets/icon.png

nav_external_links:
  - title: Taxonomy Browser
    url: https://aemann01.shinyapps.io/rpocdb_tax_browser/
    hide_icon: true 
    opens_in_new_tab: true
